#' Wrapper for pls pls functions
#'
#' Based on arguments, this wrapper preprocesses the data for `plsr` regression.
#' `plsr` takes a formula input, but requires x and y to be matrices in order to
#' handle multivariate predictors and outcomes. This wrapper thus takes
#' matrix `x` and `y` and converts them to the expected formula format
#' under the hood.
#' @param x A data frame or matrix of predictors.
#' @param y A matrix, vector, or data frame.
#' @param ncomp The number of PLS components. If left NULL, the maximum possible
#' is used.
#' @return A model object generated by [pls::plsr()].
#' @export
#' @keywords internal
plsr_fit <- function(x, y, ncomp = NULL, ...) {
  if (!is.matrix(x)) {
    x <- as.matrix(x)
  }
  if (!is.matrix(y)) {
    y <- as.matrix(y)
  }
  px <- ncol(x)
  py <- ncol(y)
  if (is.null(ncomp)) {
    ncomp <- min(px, py)
  } else {
    ncomp <- min(ncomp, px, py)
  }

  res <- pls::plsr(y ~ x, ncomp = ncomp, ...)

  res
}
